module.exports = {
  'Scene_Base': 'writable',
  'Scene_Boot': 'writable',
  'Scene_Title': 'writable',
  'Scene_Map': 'writable',
  'Scene_MenuBase': 'writable',
  'Scene_Menu': 'writable',
  'Scene_ItemBase': 'writable',
  'Scene_Item': 'writable',
  'Scene_Skill': 'writable',
  'Scene_Equip': 'writable',
  'Scene_Status': 'writable',
  'Scene_Options': 'writable',
  'Scene_File': 'writable',
  'Scene_Save': 'writable',
  'Scene_Load': 'writable',
  'Scene_GameEnd': 'writable',
  'Scene_Shop': 'writable',
  'Scene_Name': 'writable',
  'Scene_Debug': 'writable',
  'Scene_Battle': 'writable',
  'Scene_Gameover': 'writable',
};
